/** Feature columns from deployment_bundle/models/model_meta.json */
export const PEST_MODEL_FEATURE_COLUMNS = [
  "temperature",
  "humidity",
  "rainfall",
  "soil_moisture",
  "soil_ph",
  "light_intensity",
  "fertilizer_used",
  "irrigation_needed",
  "hour",
  "month",
  "location_Chattogram",
  "location_Dhaka",
  "location_Khulna",
  "location_Mymensingh",
  "location_Rajshahi",
  "location_Sylhet",
  "crop_type_Jute",
  "crop_type_Potato",
  "crop_type_Rice",
  "crop_type_Tomato",
  "crop_type_Wheat",
  "season_summer",
  "season_winter",
] as const;
